#!/bin/bash
#**************************************************************************************
#Description:   Generates a pdf from the '.dot' files that are generated by the use
#               of the ACO_DBG_REGIONS sched.ini option
#Author:        Paul McHugh
#Last Update:	July 24, 2020
#**************************************************************************************
#Must be run in the directory containing the '.dot' files you want to process
#Requires write permission in the current directory.

#check to see if we have the proper packages installed
if dot -V &> /dev/null || pdfunite -v &> /dev/null;
then
	echo -e "\e[31mYou are missing either graphviz or poppler-utils\e[m"
	echo "Install the necessary packages with the command:"
	echo -e "\e[32msudo apt install graphviz poppler-utils\e[m"
	exit
fi


regions=`ls *"@initial.dot" *"@iteration"*.dot | cut -d@ -f1 |uniq`
for region in $regions
do
	for file in $region*.dot
	do
		dot -Tpdf -o ${file%.dot}.pdf $file
	done

	rm -f $region.pdf
	pdfunite `ls -v $region*.pdf` $region.pdf
done

echo $regions
tar -czf result_pdfs.tar.gz $(printf '%q.pdf ' $regions)
